listen_addresses = '*'
port = 5432
wal_level = replica
wal_log_hints = on
max_wal_senders = 10
max_replication_slots = 10
hot_standby = on
synchronous_standby_names = 'FIRST 1 (pg_b)'
log_connections = on
log_disconnections = on
log_replication_commands = on
shared_buffers = 256MB
max_connections = 100
password_encryption = 'scram-sha-256'
restart_after_crash = off
