listen_addresses = '*'
port = 9999
socket_dir = '/var/run/postgresql'
pcp_listen_addresses = '*'
pcp_port = 9898
pcp_socket_dir = '/var/run/postgresql'
backend_clustering_mode = 'streaming_replication'
num_init_children = 32
max_pool = 4
reserved_connections = 2
enable_pool_hba = on
pool_passwd = '/etc/pgpool2/pool_passwd'
allow_clear_text_frontend_auth = off
load_balance_mode = on
statement_level_load_balance = on
sr_check_period = 5
sr_check_user = 'postgres'
sr_check_password = 'postgres'
health_check_period = 5
health_check_timeout = 10
health_check_user = 'postgres'
health_check_password = 'postgres'
backend_hostname0 = 'pg_a'
backend_port0 = 5432
backend_weight0 = 1
backend_data_directory0 = '/var/lib/postgresql/data'
backend_flag0 = 'ALLOW_TO_FAILOVER'
backend_application_name0 = 'pg_a'
backend_hostname1 = 'pg_b'
backend_port1 = 5432
backend_weight1 = 1
backend_data_directory1 = '/var/lib/postgresql/data'
backend_flag1 = 'ALLOW_TO_FAILOVER'
backend_application_name1 = 'pg_b'
backend_hostname2 = 'pg_c'
backend_port2 = 5432
backend_weight2 = 1
backend_data_directory2 = '/var/lib/postgresql/data'
backend_flag2 = 'ALLOW_TO_FAILOVER'
backend_application_name2 = 'pg_c'
log_destination = 'stderr'
logging_collector = off
failover_command = '/usr/local/bin/pgpool-failover.sh %d %P %m %H %M %N'
failover_on_backend_error = on
failover_on_backend_shutdown = on
search_primary_node_timeout = 10
