@echo off
setlocal
cd /d "%~dp0"
echo [stage1] Initializing schema...
docker compose exec cassandra-1 cqlsh -f /lab/scripts/init_schema.cql
echo [stage1] Running INSERT IF NOT EXISTS demo and CONSISTENCY ALL read check...
docker compose exec cassandra-1 cqlsh -f /lab/scripts/stage1_check.cql
echo [stage1] Checking cluster status...
docker compose exec cassandra-1 nodetool status
echo.
echo [stage1] Checking schema agreement...
docker compose exec cassandra-1 nodetool describecluster
